// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayTaxi.Infrastructure.Data;

#nullable disable

namespace PayTaxi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917131749_SettlementsAndOperatorRole")]
    partial class SettlementsAndOperatorRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("InvoiceNumberSeq")
                .StartsAt(1000000L);

            modelBuilder.Entity("PayTaxi.Core.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParkId");

                    b.ToTable("AdminUsers", t =>
                        {
                            t.HasCheckConstraint("CK_AdminUsers_Role", "\"Role\" IN ('super_admin', 'operator', 'park_admin')");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ApiAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestParamsHash")
                        .HasColumnType("text");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ParkId", "Timestamp");

                    b.ToTable("ApiAuditLogs");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.BankCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("BankType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("HolderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenReferenceEncrypted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Iban");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Cashout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BankCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankTransferId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitiatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long?>("InvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParkBankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SettlementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexReversalTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("YandexTransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankCardId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ParkBankAccountId");

                    b.HasIndex("SettlementId");

                    b.HasIndex("DriverId", "Status");

                    b.HasIndex("ParkId", "Status");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("Cashouts");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexDriverProfileId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhoneHash")
                        .IsUnique();

                    b.HasIndex("ParkId", "YandexDriverProfileId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CashoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<Guid?>("SettlementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashoutId");

                    b.HasIndex("SettlementId");

                    b.HasIndex("ParkId", "CreatedAt");

                    b.ToTable("LedgerEntries", t =>
                        {
                            t.HasCheckConstraint("CK_LedgerEntries_Owner", "(\"CashoutId\" IS NOT NULL) <> (\"SettlementId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "CreatedAt");

                    b.HasIndex("DriverId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PhoneHash");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Park", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccountIban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("BankCredentialsEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("BankType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("CashoutFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0.50m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyCashoutLimitPerDriver")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalEntityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("MaxCashoutAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinCashoutAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(5m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingModel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Phase1CapGel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Phase1SharePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SwichSharePercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(50m);

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YandexClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YandexParkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Parks", t =>
                        {
                            t.HasCheckConstraint("CK_Parks_CashoutFee_NonNegative", "\"CashoutFee\" >= 0");

                            t.HasCheckConstraint("CK_Parks_MinCashout_Positive", "\"MinCashoutAmount\" > 0");

                            t.HasCheckConstraint("CK_Parks_OperatingModel", "\"OperatingModel\" IN ('model_a', 'model_a5', 'model_b')");

                            t.HasCheckConstraint("CK_Parks_SlugFormat", "\"Slug\" ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'");

                            t.HasCheckConstraint("CK_Parks_Status", "\"Status\" IN ('pending', 'active', 'suspended', 'terminated')");

                            t.HasCheckConstraint("CK_Parks_SwichShare_Percent", "\"SwichSharePercent\" >= 0 AND \"SwichSharePercent\" <= 100");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ParkBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialsEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HolderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkId", "BankCode");

                    b.HasIndex("ParkId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.ToTable("ParkBankAccounts");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ReconciliationDiscrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankTransferId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CashoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExternalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PaytaxiAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CashoutId");

                    b.HasIndex("RunId");

                    b.HasIndex("ParkId", "IsResolved");

                    b.ToTable("ReconciliationDiscrepancies", t =>
                        {
                            t.HasCheckConstraint("CK_ReconciliationDiscrepancies_Kind", "\"Kind\" IN ('missing_in_bank', 'orphaned_bank_send', 'missing_in_yandex', 'orphaned_yandex_debit', 'amount_mismatch_bank', 'amount_mismatch_yandex', 'stuck_pending')");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BankTransfersScanned")
                        .HasColumnType("integer");

                    b.Property<int>("CashoutsScanned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscrepanciesFound")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WindowFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WindowTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YandexTxScanned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParkId", "StartedAt");

                    b.ToTable("ReconciliationRuns", t =>
                        {
                            t.HasCheckConstraint("CK_ReconciliationRuns_Status", "\"Status\" IN ('running', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("BankTransferId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CashoutCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CumulativeFeesBefore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("FeeTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("InitiatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InvoiceRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParkBankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ParkShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PeriodFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Phase1Fees")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Phase2Fees")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SwichIban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<decimal>("SwichShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ParkBankAccountId");

                    b.HasIndex("ParkId", "SettlementDate")
                        .IsUnique();

                    b.HasIndex("Status", "SettlementDate");

                    b.ToTable("Settlements", t =>
                        {
                            t.HasCheckConstraint("CK_Settlements_Status", "\"Status\" IN ('pending', 'processing', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.YandexBalanceCache", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DriverId");

                    b.ToTable("YandexBalanceCaches");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.AdminUser", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.BankCard", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithMany("BankCards")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Cashout", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.BankCard", "BankCard")
                        .WithMany()
                        .HasForeignKey("BankCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithMany("Cashouts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayTaxi.Core.Entities.ParkBankAccount", "ParkBankAccount")
                        .WithMany()
                        .HasForeignKey("ParkBankAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany("Cashouts")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayTaxi.Core.Entities.Settlement", "Settlement")
                        .WithMany("Cashouts")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankCard");

                    b.Navigation("Driver");

                    b.Navigation("Park");

                    b.Navigation("ParkBankAccount");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Driver", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany("Drivers")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.LedgerEntry", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Cashout", "Cashout")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("CashoutId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PayTaxi.Core.Entities.Settlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cashout");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Notification", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ParkBankAccount", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany("BankAccounts")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ReconciliationDiscrepancy", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Cashout", "Cashout")
                        .WithMany()
                        .HasForeignKey("CashoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayTaxi.Core.Entities.ReconciliationRun", "Run")
                        .WithMany("Discrepancies")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashout");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ReconciliationRun", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Settlement", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.ParkBankAccount", "ParkBankAccount")
                        .WithMany()
                        .HasForeignKey("ParkBankAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany("Settlements")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");

                    b.Navigation("ParkBankAccount");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.YandexBalanceCache", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithOne("BalanceCache")
                        .HasForeignKey("PayTaxi.Core.Entities.YandexBalanceCache", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Cashout", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Driver", b =>
                {
                    b.Navigation("BalanceCache");

                    b.Navigation("BankCards");

                    b.Navigation("Cashouts");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Park", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Cashouts");

                    b.Navigation("Drivers");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ReconciliationRun", b =>
                {
                    b.Navigation("Discrepancies");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Settlement", b =>
                {
                    b.Navigation("Cashouts");
                });
#pragma warning restore 612, 618
        }
    }
}
