// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayTaxi.Infrastructure.Data;

#nullable disable

namespace PayTaxi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529064101_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayTaxi.Core.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParkId");

                    b.ToTable("AdminUsers", t =>
                        {
                            t.HasCheckConstraint("CK_AdminUsers_Role", "\"Role\" IN ('super_admin', 'park_admin')");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.ApiAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestParamsHash")
                        .HasColumnType("text");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ParkId", "Timestamp");

                    b.ToTable("ApiAuditLogs");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.BankCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenReferenceEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Cashout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BankCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankTransferId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexTransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankCardId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("DriverId", "Status");

                    b.HasIndex("ParkId", "Status");

                    b.ToTable("Cashouts");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexDriverProfileId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhoneHash")
                        .IsUnique();

                    b.HasIndex("ParkId", "YandexDriverProfileId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("CashoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashoutId");

                    b.HasIndex("ParkId", "CreatedAt");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "CreatedAt");

                    b.HasIndex("DriverId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PhoneHash");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Park", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AuthorizationLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankAccountIban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("BankCredentialsEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("BankType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalEntityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingModel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YandexApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YandexClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YandexParkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Parks", t =>
                        {
                            t.HasCheckConstraint("CK_Parks_AuthorizationLimit_NonNegative", "\"AuthorizationLimit\" IS NULL OR \"AuthorizationLimit\" >= 0");

                            t.HasCheckConstraint("CK_Parks_OperatingModel", "\"OperatingModel\" IN ('model_a', 'model_a5', 'model_b')");

                            t.HasCheckConstraint("CK_Parks_SlugFormat", "\"Slug\" ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'");

                            t.HasCheckConstraint("CK_Parks_Status", "\"Status\" IN ('pending', 'active', 'suspended', 'terminated')");
                        });
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.YandexBalanceCache", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DriverId");

                    b.ToTable("YandexBalanceCaches");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.AdminUser", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany()
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.BankCard", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithMany("BankCards")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Cashout", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.BankCard", "BankCard")
                        .WithMany()
                        .HasForeignKey("BankCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithMany("Cashouts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany("Cashouts")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankCard");

                    b.Navigation("Driver");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Driver", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Park", "Park")
                        .WithMany("Drivers")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.LedgerEntry", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Cashout", "Cashout")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("CashoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashout");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Notification", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.YandexBalanceCache", b =>
                {
                    b.HasOne("PayTaxi.Core.Entities.Driver", "Driver")
                        .WithOne("BalanceCache")
                        .HasForeignKey("PayTaxi.Core.Entities.YandexBalanceCache", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Cashout", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Driver", b =>
                {
                    b.Navigation("BalanceCache");

                    b.Navigation("BankCards");

                    b.Navigation("Cashouts");
                });

            modelBuilder.Entity("PayTaxi.Core.Entities.Park", b =>
                {
                    b.Navigation("Cashouts");

                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
